### ISSUE TITLE
轮播表数据行数不够config设定的行数会报错，有什么办法呀？

### ISSUE THREAD

**Issue by liusk407** [yizhiyuyou/datav-react-doc#4]

**Comment by liusk407** [comment]
数据行数<=config中设定的rowNum时，鼠标移动到轮播表就会报错
Uncaught TypeError: resume is not a function
    at handleHover (index.js:305:1)
    at onMouseEnter (index.js:399:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
    at processDispatchQueue (react-dom.development.js:9086:1)
    at dispatchEventsForPlugins (react-dom.development.js:9097:1)
